### ISSUE TITLE
Usage In Manta

### ISSUE THREAD

**Issue by FlorianWendelborn** [obreitwi/dota2vgs#1]
Hi, just wanted to let you know, that I plan to implement this in [Manta Config Engine](https://github.com/dodekeract/manta-config-engine) and [Manta Config Engine App](https://github.com/dodekeract/manta-config-engine-app). I will leave a link in the project's [README](https://github.com/dodekeract/manta-config-engine#special-thanks) to this project and your github user-profile.

The implementation itself will probably only mirror [this particular version of d2vgs](http://www.initialcommit.org/d2vgs/sheet).

In case you find this inconvenient in any way and want me to remove this from manta or change how you're attributed, just let me know.

Have a nice day,

@dodekeract

**Comment by obreitwi** [comment]
Hi, no, that is totally fine - I currently do not have time to keep d2vgs updated anyway (I have yet to start the Reborn client, for instance)..

**Comment by FlorianWendelborn** [comment]
Thanks, will close this then.
